#!/usr/bin/env bash

###############################################################################
# This script installs the dotfiles
# @author Vlad Ghinea
###############################################################################

# Exit immediately if a command exits with a non-zero status
set -e

# Read dotfiles directory
DOTFILES="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Load system functions
[[ -s $DOTFILES/.functions ]] && source $DOTFILES/.functions || \
  ( echo '.functions file was not found'; exit 1 )

# Link dotfiles (excluding unnecessary files and including some nondot)
link_dotfiles $(find $DOTFILES -maxdepth 1 -name '.*' \
  ! -path '*/.git' \
  ! -path '*/.gitignore' \
  ! -path '*/.gitmodules' \
  ! -path '*/.DS_Store' \
  -o -name 'bin')

# Fix permissions
dotfiles_permissions

e_footer 'Done' && exit 0
