#!/usr/bin/env bash
# Common functions

# Immediately exit on errors
# set -euo pipefail

# Load all functions
for file in $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)/*.sh; do
  # shellcheck disable=1090
  . "$file" || true
done
